name: Test

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository's code

    - name: Update Ubunto
      run: apt update

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install antlr4-python3-runtime 
        
    - name: Install Antlr4
      run: apt-get install antlr4 

    - name: Permission script
      run: chmod +x run_tests.sh
      
    - name: Run tests
      run: ./run_tests.sh
